import json
import os
import re
import string
import webvtt
from pathlib import Path

from elasticsearch import Elasticsearch
from elasticsearch.helpers import bulk, scan
client = Elasticsearch('http://localhost:9200')

def fix_youtube_vtt(vtt_file_path) -> str:
    """Fixes Youtube's autogenerated VTT subtitles and returns a vtt-formatted string"""
    """Adapted from: https://github.com/yt-dlp/yt-dlp/issues/1734"""
    pretty_subtitle = "WEBVTT\n\n"
    previous_caption_text = ""
    previous_caption_start = None
    previous_caption_end = None
    i = 1  # kept so it looks like your original

    for caption in webvtt.read(vtt_file_path):
        current_text = caption.text.strip()
        current_lines = current_text.split("\n")

        if not current_text:
            continue

        if previous_caption_text == current_text:
            # identical -> just extend the end time
            previous_caption_end = caption.end

        elif previous_caption_text == current_lines[0] and len(current_lines) > 1:
            # overlap multi-line: prev == first line, keep the second line as the "current"
            # flush previous cue first
            if previous_caption_start is not None:
                pretty_subtitle += (
                    f"{previous_caption_start} --> {previous_caption_end}\n"
                    f"{previous_caption_text}\n\n"
                )
                i += 1

            previous_caption_text = current_lines[1].strip()
            previous_caption_start = caption.start.strip()
            previous_caption_end = caption.end.strip()

        else:
            # new different caption -> flush previous cue, then start a new one
            if previous_caption_start is not None:
                pretty_subtitle += (
                    f"{previous_caption_start} --> {previous_caption_end}\n"
                    f"{previous_caption_text}\n\n"
                )
                i += 1

            previous_caption_text = current_text
            previous_caption_start = caption.start.strip()
            previous_caption_end = caption.end.strip()

    # flush final pending cue
    if previous_caption_start is not None and previous_caption_text.strip():
        pretty_subtitle += (
            f"{previous_caption_start} --> {previous_caption_end}\n"
            f"{previous_caption_text}\n\n"
        )

    return pretty_subtitle

def ts_to_seconds(ts: str) -> float:
    m = re.match(r"(\d{2}):(\d{2}):(\d{2})\.(\d{3})", ts.strip())
    if not m:
        raise ValueError(f"Bad timestamp: {ts!r}")
    hh, mm, ss, ms = map(int, m.groups())
    return hh * 3600 + mm * 60 + ss + ms / 1000.0

def seconds_to_ts(seconds: float) -> str:
    if seconds < 0:
        seconds = 0.0
    ms_total = int(round(seconds * 1000))
    hh = ms_total // (3600 * 1000)
    ms_total %= 3600 * 1000
    mm = ms_total // (60 * 1000)
    ms_total %= 60 * 1000
    ss = ms_total // 1000
    ms = ms_total % 1000
    return f"{hh:02d}:{mm:02d}:{ss:02d}.{ms:03d}"

def chunk_captions(captions, max_s = 30, overlap_s = 10):
    """Chunks captions into segments of max_s seconds, with overlap_s seconds of overlap"""
    chunks = []
    current_chunk = []
    current_chunk_start = None
    current_chunk_end = None

    for caption in captions:
        caption_start_s = ts_to_seconds(caption.start)
        caption_end_s = ts_to_seconds(caption.end)

        if current_chunk_start is None:
            # start the first chunk
            current_chunk_start = caption_start_s
            current_chunk_end = caption_end_s
            current_chunk.append(caption)
        elif caption_start_s - current_chunk_start <= max_s:
            # still within the max chunk duration, add to current chunk
            current_chunk.append(caption)
            current_chunk_end = max(current_chunk_end, caption_end_s)
        else:
            # chunk is full, save it and start a new one with overlap
            chunk = {
                "start_time": seconds_to_ts(current_chunk_start),
                "end_time": seconds_to_ts(current_chunk_end),
                "start_seconds": current_chunk_start,
                "end_seconds": current_chunk_end,
                "text": "\n".join(c.text for c in current_chunk)
            }
            
            chunks.append(chunk)
            # start new chunk with overlap
            current_chunk_start = caption_start_s - overlap_s
            if current_chunk_start < 0:
                current_chunk_start = 0.0
            current_chunk_end = caption_end_s
            current_chunk = [caption]

    # add the final chunk if it exists
    if current_chunk:
        chunk = {
            "start_time": seconds_to_ts(current_chunk_start),
            "end_time": seconds_to_ts(current_chunk_end),
            "start_seconds": current_chunk_start,
            "end_seconds": current_chunk_end,
            "text": "\n".join(c.text for c in current_chunk)
        }
        chunks.append(chunk)

    return chunks

if __name__ == "__main__":
    path = input("Enter the path to the directory containing the transcripts: ")
    name = input("Enter the name of the collection: ")
    
    # Elasticsearch setup
    INDEX_NAME = "transcript_" + name.replace(" ", "_").lower()
    if not client.indices.exists(index=INDEX_NAME):
        client.indices.create(index=INDEX_NAME, body={
            "settings": {
                "analysis": {
                    "analyzer": {
                        "english": {
                            "type": "standard",
                            "stopwords": "_english_"
                        }
                    }
                }
            },
            "mappings": {
                "properties": {
                    "video_id": {"type": "keyword"},
                    "start_time": {"type": "keyword"},
                    "end_time": {"type": "keyword"},
                    "start_seconds": {"type": "float"},
                    "end_seconds": {"type": "float"},
                    "text": {"type": "text",
                             "analyzer": "english"
                             }
                }
            }
        })
    
    transcripts = os.listdir(path)
    TRANSCRIPT_DIR = Path(path)
    
    for transcript_file in transcripts:
        if not transcript_file.endswith(".en.vtt"):
            continue
        print(f"\nTranscript file: {transcript_file}") 
        video_id = re.search(r"\[([^\[\]]+)\]\.en\.vtt$", transcript_file).group(1)
        print(f"Video ID: {video_id}")
        
        fixed_subtitle = fix_youtube_vtt(TRANSCRIPT_DIR / transcript_file)
                
        captions = list(webvtt.from_string(fixed_subtitle))
        chunks = chunk_captions(captions)
        actions = []
        for chunk in chunks:
            action = {
                "_index": INDEX_NAME,
                "_source": {
                    "video_id": video_id,
                    "start_time": chunk["start_time"],
                    "end_time": chunk["end_time"],
                    "start_seconds": chunk["start_seconds"],
                    "end_seconds": chunk["end_seconds"],
                    "text": chunk["text"]
                }
            }
            actions.append(action)
        bulk(client, actions)
    print(f"\nFinished processing {len(transcripts)} transcripts into index '{INDEX_NAME}'")
            