import json
import os
import webvtt
from pathlib import Path

TRANSCRIPT_DIR = Path("transcripts")
PLAYLIST_ID = "PLlDdLy-1g17aiMmEw63_K4Gf-gq_0AJhI"
PLAYLIST_NAME = "Just Roll With It - The Black Rose Pirates"
# PLAYLIST_NAME = "NeetCode - Sliding Window"

transcripts = os.listdir(TRANSCRIPT_DIR / PLAYLIST_NAME)

def fix_youtube_vtt(vtt_file_path) -> str:
    """Fixes Youtube's autogenerated VTT subtitles and returns a vtt-formatted string"""
    """Adapted from: https://github.com/yt-dlp/yt-dlp/issues/1734"""
    pretty_subtitle = "WEBVTT\n\n"
    previous_caption_text = ""
    previous_caption_start = None
    previous_caption_end = None
    i = 1  # kept so it looks like your original

    for caption in webvtt.read(vtt_file_path):
        current_text = caption.text.strip()
        current_lines = current_text.split("\n")

        if not current_text:
            continue

        if previous_caption_text == current_text:
            # identical -> just extend the end time
            previous_caption_end = caption.end

        elif previous_caption_text == current_lines[0] and len(current_lines) > 1:
            # overlap multi-line: prev == first line, keep the second line as the "current"
            # flush previous cue first
            if previous_caption_start is not None:
                pretty_subtitle += (
                    f"{previous_caption_start} --> {previous_caption_end}\n"
                    f"{previous_caption_text}\n\n"
                )
                i += 1

            previous_caption_text = current_lines[1].strip()
            previous_caption_start = caption.start.strip()
            previous_caption_end = caption.end.strip()

        else:
            # new different caption -> flush previous cue, then start a new one
            if previous_caption_start is not None:
                pretty_subtitle += (
                    f"{previous_caption_start} --> {previous_caption_end}\n"
                    f"{previous_caption_text}\n\n"
                )
                i += 1

            previous_caption_text = current_text
            previous_caption_start = caption.start.strip()
            previous_caption_end = caption.end.strip()

    # flush final pending cue
    if previous_caption_start is not None and previous_caption_text.strip():
        pretty_subtitle += (
            f"{previous_caption_start} --> {previous_caption_end}\n"
            f"{previous_caption_text}\n\n"
        )

    return pretty_subtitle


for transcript_file in transcripts:
    if not transcript_file.endswith(".en.vtt"):
        continue
    print(f"\nTranscript file: {transcript_file}")
    
    fixed_subtitle = fix_youtube_vtt(TRANSCRIPT_DIR / PLAYLIST_NAME / transcript_file)
    print(fixed_subtitle)
    
    for caption in webvtt.from_string(fixed_subtitle):
        print(f"[{caption.start} --> {caption.end}] {caption.text}")
    
    
    
    # vtt = webvtt.read(TRANSCRIPT_DIR / PLAYLIST_NAME / transcript_file)
    
    # for i, caption in enumerate(vtt):
    #     if i >= 15:
    #         break
    #     print(f"[{caption.start} --> {caption.end}] {caption.text}")